apiVersion: v1
kind: Service
metadata:
  name: smartfarmapp-svc
  labels:
    app: smartfarmapp
    name: smartfarmapp
spec:
  ports:
    - port: 5000
  selector:
    app: smartfarmapp
  type: ClusterIP